import type { UserKnowledgeContext, FAQItem } from '@/lib/types/knowledge-context';
import { EMPTY_KNOWLEDGE_CONTEXT } from '@/lib/types/knowledge-context';

/**
 * Represents a row from the public.user_knowledge_wiki table
 * Built by previous analyses via the question capture flow (Wave 4.1).
 * Stores aggregated wiki articles (one per topic) with markdown content.
 */
interface WikiRow {
  id: string;
  user_id: string;
  topic: string;
  wiki_markdown: string;
  question_count: number;
  theme_count: number;
  created_at: string;
  updated_at: string;
}

/**
 * Port interface for accessing user knowledge wiki data.
 * Allows this service to be decoupled from specific persistence implementation.
 */
export interface KnowledgeWikiPort {
  /**
   * Load all Q/A records for a user from their knowledge wiki.
   * Returns empty array if user has no history.
   */
  getUserWiki(userId: string): Promise<WikiRow[]>;
}

export class KnowledgeHistoryService {
  constructor(private wikiPort: KnowledgeWikiPort) {}

  /**
   * Load and extract user's learning context from their knowledge wiki.
   * - Extracts top 3-5 themes (by frequency)
   * - Parses wiki_markdown to extract real FAQ items (questions and answers)
   * - For each theme, extracts top 3-5 FAQ items (by relevance/frequency)
   * - Builds a summary string of learning activity
   *
   * Gracefully handles:
   * - User with no wiki history (returns EMPTY_KNOWLEDGE_CONTEXT)
   * - Malformed wiki markdown (logs warning, uses fallback)
   * - Wiki with no parseable FAQs (still returns themes)
   * - Repeated themes (deduplicates and counts frequency)
   *
   * FAQ Extraction from Markdown:
   * The wiki_markdown format is generated by wiki-builder and contains:
   *   # {Month Name} Knowledge Wiki
   *   ## {Theme}
   *   ### FAQ
   *   - Question 1
   *   - Question 2
   *   ### Common Keywords
   *   keyword1, keyword2, ...
   *
   * This service extracts questions from the "### FAQ" sections and pairs them with
   * theme information and question count as a proxy for relevance.
   */
  async loadUserKnowledgeContext(userId: string): Promise<UserKnowledgeContext> {
    try {
      const wiki = await this.wikiPort.getUserWiki(userId);

      // Empty history
      if (!wiki || wiki.length === 0) {
        return EMPTY_KNOWLEDGE_CONTEXT;
      }

      // Extract themes from wiki topics, ranked by question count
      const themeEntries = wiki
        .map((row) => ({
          theme: row.topic.trim() || 'General',
          score: row.question_count || 1,
          markdown: row.wiki_markdown || '',
        }))
        .filter((entry) => entry.theme);

      // Get top 3-5 themes by question count
      const topThemes = themeEntries
        .sort((a, b) => b.score - a.score)
        .slice(0, 5)
        .map((entry) => entry.theme);

      // Build FAQ items by parsing wiki markdown
      const topFaqs: FAQItem[] = extractFAQsFromWiki(themeEntries);

      // Build learning summary
      const totalTopics = wiki.length;
      const totalQuestions = wiki.reduce((sum, row) => sum + (row.question_count || 0), 0);
      const learningSummary =
        totalQuestions > 0
          ? `You've previously asked about: ${topThemes.join(', ')} (${totalQuestions} questions across ${totalTopics} topics)`
          : '';

      return {
        themes: topThemes,
        faqs: topFaqs,
        learningSummary,
      };
    } catch (error) {
      console.error('[KnowledgeHistoryService] Error loading user wiki:', error);
      // Fail gracefully — return empty context if wiki fetch fails
      return EMPTY_KNOWLEDGE_CONTEXT;
    }
  }
}

/**
 * Extract FAQ items from parsed wiki markdown.
 *
 * Expected format per theme section:
 * ## {Theme Name}
 * **Questions in this theme:** N
 *
 * ### FAQ
 * - Question 1
 * - Question 2
 * ...
 *
 * ### Common Keywords
 * keyword1, keyword2, ...
 *
 * Returns up to 5 FAQ items total, ranked by theme score (question_count).
 * Each FAQ item pairs a theme with an extracted question and uses the theme's
 * question_count as a proxy for relevance.
 *
 * Edge Cases Handled:
 * - Missing FAQ section: theme is skipped (no questions to extract)
 * - Malformed markdown: logs warning, extracts what is parseable
 * - Empty markdown: skipped with warning
 * - Duplicate questions: included (not deduplicated across themes)
 */
function extractFAQsFromWiki(
  themeEntries: Array<{ theme: string; score: number; markdown: string }>
): FAQItem[] {
  const allFaqs: FAQItem[] = [];

  for (const entry of themeEntries) {
    if (!entry.markdown || entry.markdown.trim() === '') {
      continue;
    }

    try {
      // Find the ### FAQ section for this theme
      const faqMatch = entry.markdown.match(/### FAQ\s*\n([\s\S]*?)(?=###|$)/);
      if (!faqMatch || !faqMatch[1]) {
        // No FAQ section found, skip this theme
        continue;
      }

      const faqSection = faqMatch[1];

      // Extract all lines that start with "- " (list items)
      const questionLines = faqSection
        .split('\n')
        .filter((line) => line.trim().startsWith('- '))
        .map((line) => line.replace(/^-\s+/, '').trim())
        .filter((q) => q.length > 0);

      // Create FAQ items from extracted questions
      for (const question of questionLines) {
        // Truncate very long questions to keep them useful as FAQs
        const displayQuestion = question.length > 200 ? question.substring(0, 200) + '...' : question;

        allFaqs.push({
          theme: entry.theme,
          question: displayQuestion,
          answer: entry.theme, // Answer is theme name (summary of what this theme covers)
          relevanceScore: entry.score,
        });
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      console.warn(`[KnowledgeHistoryService] Failed to extract FAQs from theme "${entry.theme}":`, msg);
      continue;
    }
  }

  // Sort by relevance score (question_count) and return top 5
  return allFaqs.sort((a, b) => (b.relevanceScore || 0) - (a.relevanceScore || 0)).slice(0, 5);
}
