import type { UserKnowledgeContext, FAQItem } from '@/lib/types/knowledge-context';
import { EMPTY_KNOWLEDGE_CONTEXT } from '@/lib/types/knowledge-context';

/**
 * Represents a row from the public.user_knowledge_wiki table
 * Built by previous analyses via the question capture flow (Wave 4.1).
 * Stores aggregated wiki articles (one per topic) with markdown content.
 */
interface WikiRow {
  id: string;
  user_id: string;
  topic: string;
  wiki_markdown: string;
  question_count: number;
  theme_count: number;
  created_at: string;
  updated_at: string;
}

/**
 * Port interface for accessing user knowledge wiki data.
 * Allows this service to be decoupled from specific persistence implementation.
 */
export interface KnowledgeWikiPort {
  /**
   * Load all Q/A records for a user from their knowledge wiki.
   * Returns empty array if user has no history.
   */
  getUserWiki(userId: string): Promise<WikiRow[]>;
}

export class KnowledgeHistoryService {
  constructor(private wikiPort: KnowledgeWikiPort) {}

  /**
   * Load and extract user's learning context from their knowledge wiki.
   * - Extracts top 3-5 themes (by frequency)
   * - Parses wiki_markdown to extract real FAQ items (questions and answers)
   * - For each theme, extracts top 3-5 FAQ items (by relevance/frequency)
   * - Builds a summary string of learning activity
   *
   * Gracefully handles:
   * - User with no wiki history (returns EMPTY_KNOWLEDGE_CONTEXT)
   * - Malformed wiki markdown (logs warning, uses fallback)
   * - Wiki with no parseable FAQs (still returns themes)
   * - Repeated themes (deduplicates and counts frequency)
   *
   * FAQ Extraction from Markdown:
   * The wiki_markdown format is generated by wiki-builder and contains:
   *   # {Month Name} Knowledge Wiki
   *   ## {Theme}
   *   ### FAQ
   *   - Question 1
   *   - Question 2
   *   ### Common Keywords
   *   keyword1, keyword2, ...
   *
   * This service extracts questions from the "### FAQ" sections and pairs them with
   * theme information and question count as a proxy for relevance.
   */
  /**
   * Load user knowledge context with a 3-second timeout guard.
   * If wiki lookup takes too long, returns empty context instead of blocking.
   *
   * P0 Risk #2 Fix: Wiki parsing robustness
   * - Timeout prevents blocking chat message processing
   * - Gracefully falls back to empty context on timeout
   * - Logs timeout for observability and debugging
   */
  async loadUserKnowledgeContext(userId: string): Promise<UserKnowledgeContext> {
    try {
      // Defensive timeout: if wiki lookup doesn't complete in 3s, give up
      // and return empty context. This ensures chat never hangs waiting for wiki.
      let wiki: any[] | undefined;
      try {
        wiki = await Promise.race([
          this.wikiPort.getUserWiki(userId),
          new Promise<never>((_, reject) =>
            setTimeout(() => reject(new Error('Wiki lookup timeout (3s)')), 3000)
          ),
        ]);
      } catch (timeoutError) {
        const msg = timeoutError instanceof Error ? timeoutError.message : String(timeoutError);
        if (msg.includes('timeout')) {
          console.warn('[KnowledgeHistoryService] Wiki lookup timeout, returning empty context', { userId });
          return EMPTY_KNOWLEDGE_CONTEXT;
        }
        throw timeoutError;
      }

      // Empty history
      if (!wiki || wiki.length === 0) {
        return EMPTY_KNOWLEDGE_CONTEXT;
      }

      // Extract themes from wiki topics, ranked by question count
      const themeEntries = wiki
        .map((row) => ({
          theme: row.topic.trim() || 'General',
          score: row.question_count || 1,
          markdown: row.wiki_markdown || '',
        }))
        .filter((entry) => entry.theme);

      // Get top 3-5 themes by question count
      const topThemes = themeEntries
        .sort((a, b) => b.score - a.score)
        .slice(0, 5)
        .map((entry) => entry.theme);

      // Build FAQ items by parsing wiki markdown
      const topFaqs: FAQItem[] = extractFAQsFromWiki(themeEntries);

      // Build learning summary
      const totalTopics = wiki.length;
      const totalQuestions = wiki.reduce((sum, row) => sum + (row.question_count || 0), 0);
      const learningSummary =
        totalQuestions > 0
          ? `You've previously asked about: ${topThemes.join(', ')} (${totalQuestions} questions across ${totalTopics} topics)`
          : '';

      return {
        themes: topThemes,
        faqs: topFaqs,
        learningSummary,
      };
    } catch (error) {
      console.error('[KnowledgeHistoryService] Error loading user wiki:', error);
      // Fail gracefully — return empty context if wiki fetch fails
      return EMPTY_KNOWLEDGE_CONTEXT;
    }
  }
}

/**
 * Extract FAQ items from parsed wiki markdown.
 *
 * Expected format per theme section:
 * ## {Theme Name}
 * **Questions in this theme:** N
 *
 * ### FAQ
 * - Question 1
 * - Question 2
 * ...
 *
 * ### Common Keywords
 * keyword1, keyword2, ...
 *
 * Returns up to 5 FAQ items total, ranked by theme score (question_count).
 * Each FAQ item pairs a theme with an extracted question and uses the theme's
 * question_count as a proxy for relevance.
 *
 * P0 Risk #2 Fix: Wiki parsing robustness
 * Edge Cases Handled:
 * - Missing FAQ section: theme is skipped (no questions to extract)
 * - Malformed markdown: logs warning, extracts what is parseable, skips bad row
 * - Empty markdown: skipped silently
 * - Duplicate questions: included (not deduplicated across themes)
 * - Null/undefined theme: sanitized to 'General'
 * - Non-string markdown: skipped with type warning
 * - Invalid question format: filtered out, doesn't corrupt row
 */
function extractFAQsFromWiki(
  themeEntries: Array<{ theme: string; score: number; markdown: string }>
): FAQItem[] {
  const allFaqs: FAQItem[] = [];

  for (const entry of themeEntries) {
    // Defensive: skip malformed entries early
    if (!entry || typeof entry.markdown !== 'string') {
      if (entry && entry.theme) {
        console.warn(`[KnowledgeHistoryService] Skipping theme "${entry.theme}": markdown is not a string`);
      }
      continue;
    }

    if (entry.markdown.trim() === '') {
      continue;
    }

    try {
      // Sanitize theme name (fallback to 'General' if missing)
      const sanitizedTheme = (entry.theme || '').trim() || 'General';

      // Find the ### FAQ section for this theme (defensive against malformed headers)
      const faqMatch = entry.markdown.match(/### FAQ\s*\n([\s\S]*?)(?=###|$)/);

      if (!faqMatch || !faqMatch[1]) {
        // No FAQ section found, skip this theme silently (not an error)
        continue;
      }

      const faqSection = faqMatch[1];

      // Extract all lines that start with "- " (list items)
      const questionLines: string[] = [];
      faqSection
        .split('\n')
        .forEach((line) => {
          if (!line || typeof line !== 'string') return;
          if (line.trim().startsWith('- ')) {
            const q = line.replace(/^-\s+/, '').trim();
            // Validate question: non-empty, reasonable length (3-500 chars), no binary/null bytes
            if (q.length > 0 && q.length <= 500 && !/[\x00-\x1f]/.test(q)) {
              questionLines.push(q);
            }
          }
        });

      // Create FAQ items from extracted questions
      for (const question of questionLines) {
        try {
          // Truncate very long questions to keep them useful as FAQs
          const displayQuestion = question.length > 200 ? question.substring(0, 200) + '...' : question;

          allFaqs.push({
            theme: sanitizedTheme,
            question: displayQuestion,
            answer: sanitizedTheme, // Answer is theme name (summary of what this theme covers)
            relevanceScore: entry.score || 1,
          });
        } catch (faqError) {
          // Skip individual FAQ item on error, don't corrupt the row
          console.warn(`[KnowledgeHistoryService] Failed to add FAQ for theme "${sanitizedTheme}":`,
            faqError instanceof Error ? faqError.message : String(faqError));
          continue;
        }
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      const themeName = (entry && entry.theme) || 'unknown';
      console.warn(`[KnowledgeHistoryService] Failed to extract FAQs from theme "${themeName}":`, msg);
      // Continue to next theme — one bad row doesn't break others
      continue;
    }
  }

  // Sort by relevance score (question_count) and return top 5
  // P0 Risk #3 Fix: History injection token budget is enforced at buildGroundingWithHistory level
  return allFaqs.sort((a, b) => (b.relevanceScore || 0) - (a.relevanceScore || 0)).slice(0, 5);
}
