/**
 * Error Code Registry
 * Centralized dictionary of all failure modes for consistent logging and Sentry tagging.
 * Format: ERR_CATEGORY_SPECIFIC_FAILURE
 */

export const ERROR_CODES = {
  // Authentication & Authorization
  AUTH_UNAUTHORIZED: 'ERR_AUTH_UNAUTHORIZED',
  AUTH_SESSION_INVALID: 'ERR_AUTH_SESSION_INVALID',
  AUTH_MISSING_USER_ID: 'ERR_AUTH_MISSING_USER_ID',

  // Rate Limiting & Quotas
  RATE_LIMIT_EXCEEDED: 'ERR_RATE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED: 'ERR_QUOTA_EXCEEDED',
  QUOTA_FETCH_FAILED: 'ERR_QUOTA_FETCH_FAILED',
  TIER_NULL: 'ERR_TIER_NULL',
  TIER_FETCH_FAILED: 'ERR_TIER_FETCH_FAILED',

  // Input Validation
  INVALID_JSON: 'ERR_INVALID_JSON',
  INVALID_REQUEST_SCHEMA: 'ERR_INVALID_REQUEST_SCHEMA',
  INVALID_VIDEO_URL: 'ERR_INVALID_VIDEO_URL',
  INVALID_VIDEO_ID: 'ERR_INVALID_VIDEO_ID',

  // External Services
  CLOUDFLARE_WORKER_ERROR: 'ERR_CLOUDFLARE_WORKER_ERROR',
  CLOUDFLARE_TRANSCRIPT_NOT_FOUND: 'ERR_CLOUDFLARE_TRANSCRIPT_NOT_FOUND',
  CLOUDFLARE_METADATA_INVALID: 'ERR_CLOUDFLARE_METADATA_INVALID',
  CLOUDFLARE_SSRF_BLOCKED: 'ERR_CLOUDFLARE_SSRF_BLOCKED',
  OPENROUTER_TIMEOUT: 'ERR_OPENROUTER_TIMEOUT',
  OPENROUTER_RATE_LIMIT: 'ERR_OPENROUTER_RATE_LIMIT',
  OPENROUTER_UNAVAILABLE: 'ERR_OPENROUTER_UNAVAILABLE',
  QSTASH_QUEUE_FAILED: 'ERR_QSTASH_QUEUE_FAILED',
  QSTASH_PUBLISH_FAILED: 'ERR_QSTASH_PUBLISH_FAILED',

  // Database Operations
  DATABASE_CACHE_LOOKUP_FAILED: 'ERR_DATABASE_CACHE_LOOKUP_FAILED',
  DATABASE_USER_FETCH_FAILED: 'ERR_DATABASE_USER_FETCH_FAILED',
  DATABASE_ANALYSIS_INSERT_FAILED: 'ERR_DATABASE_ANALYSIS_INSERT_FAILED',
  DATABASE_ANALYSIS_UPDATE_FAILED: 'ERR_DATABASE_ANALYSIS_UPDATE_FAILED',
  DATABASE_USAGE_LOG_FAILED: 'ERR_DATABASE_USAGE_LOG_FAILED',

  // Environment & Configuration
  ENV_MISSING_VARIABLE: 'ERR_ENV_MISSING_VARIABLE',
  ENV_INVALID_VALUE: 'ERR_ENV_INVALID_VALUE',
  ENV_INCOMPLETE_CONFIG: 'ERR_ENV_INCOMPLETE_CONFIG',

  // Analysis Processing
  ANALYSIS_GENERATION_FAILED: 'ERR_ANALYSIS_GENERATION_FAILED',
  ANALYSIS_STREAMING_FAILED: 'ERR_ANALYSIS_STREAMING_FAILED',
  ANALYSIS_MARKDOWN_EMPTY: 'ERR_ANALYSIS_MARKDOWN_EMPTY',
  ANALYSIS_TIMEOUT: 'ERR_ANALYSIS_TIMEOUT',
  ANALYSIS_PERSONA_INVALID: 'ERR_ANALYSIS_PERSONA_INVALID',

  // Server Errors
  INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
  UNHANDLED_EXCEPTION: 'ERR_UNHANDLED_EXCEPTION',
  REQUEST_HANDLER_ERROR: 'ERR_REQUEST_HANDLER_ERROR',

  // Search Operations
  SEARCH_QUERY_INVALID: 'ERR_SEARCH_QUERY_INVALID',
  SEARCH_VECTOR_FAILED: 'ERR_SEARCH_VECTOR_FAILED',
  SEARCH_DATABASE_FAILED: 'ERR_SEARCH_DATABASE_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Error context for structured logging
 */
export interface ErrorContext {
  code: ErrorCode;
  message: string;
  userId?: string;
  videoId?: string;
  statusCode?: number;
  details?: Record<string, unknown>;
  stack?: string;
}

/**
 * Create a standardized error context
 */
export function createErrorContext(
  code: ErrorCode,
  message: string,
  context?: Partial<Omit<ErrorContext, 'code' | 'message'>>
): ErrorContext {
  return {
    code,
    message,
    ...context,
  };
}
