version = 1

[analyzers.javascript]
environment = ["nodejs"]

[analyzers.javascript.issues]
disabled = ["JS-0857", "JS-0827", "JS-0838"]

[analyzers.meta]
skip_doc_coverage = ["function-declaration"]
