name: Setup Environment
description: "Sets up Node.js, pnpm, and installs dependencies"
inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  pnpm-version:
    description: "pnpm version"
    required: false
    default: "9.1.0"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      run: cd web && pnpm install --frozen-lockfile
      shell: bash