import { describe, it, expect, beforeEach } from 'vitest';
import { useSynthesisNucleus } from '@/lib/stores/synthesis-nucleus-store';
import { mapHistoryOverviewRow, type RawHistoryOverviewRow } from '@/lib/utils/history-overview';
import { auxStatusFromAnalysisPayload, type AuxStatusPayloadInput } from '@/lib/utils/aux-status-from-report';

const BASE_ROW: RawHistoryOverviewRow = {
  base_video_id: 'v123',
  latest_analysis_id: 'a123',
  title: 'Sample Video',
  channel_title: 'Sample Channel',
  first_analyzed_at: '2026-08-07T00:00:00Z',
  last_analyzed_at: '2026-08-07T00:00:00Z',
  last_viewed_at: null,
  times_analyzed: 1,
  views: 1,
  best_dimensions: 11,
  present_dimensions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  status: 'complete',
  has_digest: true,
  has_description: false,
  has_channel_meta: false,
  has_comments: false,
  has_chapters: true,
  client_platform: 'desktop',
};

describe('Chip State Sync Contract', () => {
  beforeEach(() => {
    useSynthesisNucleus.getState().reset();
  });

  // These table-driven cases are independently-authored SQL/RPC-shaped rows
  // (has_description/has_channel_meta/has_comments set by hand), NOT derived
  // from auxStatusFromAnalysisPayload's own output -- if this table were
  // generated by the function under test, agreement would be tautological
  // (Cubic review, PR #214: "false confidence" finding).
  const cases: Array<{
    name: string;
    row: Pick<RawHistoryOverviewRow, 'has_description' | 'has_channel_meta' | 'has_comments'>;
    payload: AuxStatusPayloadInput | null;
  }> = [
    {
      name: 'empty-string description, populated channelMeta, empty comments',
      row: { has_description: false, has_channel_meta: true, has_comments: false },
      payload: { videoMetadata: { description: '' }, channelMeta: { subscriberCount: 1000 }, comments: [] },
    },
    {
      name: 'whitespace-only description counts as absent',
      row: { has_description: false, has_channel_meta: false, has_comments: false },
      payload: { videoMetadata: { description: '   ' }, channelMeta: null, comments: [] },
    },
    {
      name: 'real description, empty channelMeta object counts as absent, non-empty comments',
      row: { has_description: true, has_channel_meta: false, has_comments: true },
      payload: { videoMetadata: { description: 'A real description' }, channelMeta: {}, comments: [{ text: 'hi' }] },
    },
    {
      name: 'all fields absent from payload entirely (not just falsy)',
      row: { has_description: false, has_channel_meta: false, has_comments: false },
      payload: {},
    },
    {
      name: 'null payload (analysis_payload column itself is null)',
      row: { has_description: false, has_channel_meta: false, has_comments: false },
      payload: null,
    },
  ];

  it.each(cases)('agrees with the SQL-shaped row for: $name', ({ row, payload }) => {
    const historyItem = mapHistoryOverviewRow({ ...BASE_ROW, ...row });
    const auxStatus = auxStatusFromAnalysisPayload(payload);

    expect(historyItem.hasDescription).toBe(auxStatus.hasDescription);
    expect(historyItem.hasChannelMeta).toBe(auxStatus.hasChannelMeta);
    expect(historyItem.hasComments).toBe(auxStatus.hasComments);
  });

  it('populates rawAnalysisPayload + rawAnalysisPayloadId in the store on initializeAnalysis with analysisPayload', () => {
    const payload = {
      videoMetadata: { description: 'Full video description here' },
      channelMeta: { subscriberCount: 50000 },
      comments: [{ text: 'Great video' }],
    };

    useSynthesisNucleus.getState().initializeAnalysis({
      id: 'a123',
      videoId: 'v123',
      title: 'Restored Video',
      analysisPayload: payload,
    });

    const state = useSynthesisNucleus.getState();
    expect(state.rawAnalysisPayload).toBe(payload);
    expect(state.rawAnalysisPayloadId).toBe('a123');

    const auxStatus = auxStatusFromAnalysisPayload(state.rawAnalysisPayload);
    expect(auxStatus.hasDescription).toBe(true);
    expect(auxStatus.hasChannelMeta).toBe(true);
    expect(auxStatus.hasComments).toBe(true);
  });

  it('clears rawAnalysisPayload and rawAnalysisPayloadId on reset', () => {
    useSynthesisNucleus.getState().initializeAnalysis({
      id: 'a123',
      videoId: 'v123',
      title: 'Restored Video',
      analysisPayload: { videoMetadata: { description: 'Video 1' } },
    });

    expect(useSynthesisNucleus.getState().rawAnalysisPayload).not.toBeNull();
    expect(useSynthesisNucleus.getState().rawAnalysisPayloadId).toBe('a123');

    useSynthesisNucleus.getState().reset();
    expect(useSynthesisNucleus.getState().rawAnalysisPayload).toBeNull();
    expect(useSynthesisNucleus.getState().rawAnalysisPayloadId).toBeNull();
  });

  it('switching from analysis A (has payload) to analysis B (no payload yet) does not leak A\'s payload as B\'s', () => {
    useSynthesisNucleus.getState().initializeAnalysis({
      id: 'a-video-1',
      videoId: 'v1',
      title: 'Video 1',
      analysisPayload: { videoMetadata: { description: 'Video 1 description' } },
    });
    expect(useSynthesisNucleus.getState().rawAnalysisPayloadId).toBe('a-video-1');

    // Switching to a genuinely different analysis with NO analysisPayload
    // yet (e.g. the fetch hasn't resolved) -- isSwitchingAnalysis resets the
    // whole metadata store, so B must not see A's payload/id.
    useSynthesisNucleus.getState().initializeAnalysis({
      id: 'b-video-2',
      videoId: 'v2',
      title: 'Video 2',
    });

    const state = useSynthesisNucleus.getState();
    expect(state.rawAnalysisPayloadId).not.toBe('a-video-1');
    expect(state.rawAnalysisPayload).toBeNull();
  });
});
