/**
 * useKnowledgeGraph — derives the knowledge graph from the Synthesis Nucleus.
 *
 * The graph is a VIEW over the full analysis (all dimensions present in the raw
 * payload), recomputed only when dimension content actually changes. Persona is
 * surfaced as node.inPersona (highlight), not as a filter — the graph always shows
 * the complete knowledge structure. Synthesis runs client-side (TF-IDF) and is
 * cheap, but we still gate it to completed/near-complete analyses to avoid churning
 * on every streamed token.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import { useSynthesisNucleus } from '@/lib/stores/synthesis-nucleus-store';
import { PERSONA_DIMENSIONS } from '@/lib/types/persona';
import { KnowledgeGraphSynthesizer } from '@/lib/intelligence/knowledge-graph';
import { TfIdfSimilarityEngine } from '@/lib/intelligence/similarity';
import type { KnowledgeGraph, GraphNode, GraphEdge } from '@/lib/types/knowledge-graph';

const EMPTY: KnowledgeGraph = { nodes: [], edges: [], rootId: null };

// Default dimension used for knowledge-graph extraction fallback (Dimension 8)
const DEFAULT_KG_EXTRACTION_DIMENSION = 8;

// Single engine + synthesizer instance (stateless, safe to reuse).
const synthesizer = new KnowledgeGraphSynthesizer(new TfIdfSimilarityEngine());

export function useKnowledgeGraph(analysisId?: string | null): { graph: KnowledgeGraph; ready: boolean; loading: boolean } {
  const analysis = useSynthesisNucleus((s) => s.analysis);
  const activePersona = useSynthesisNucleus((s) => s.activePersona);
  const storeKnowledgeGraph = useSynthesisNucleus((s) => s.knowledgeGraph);
  const [loading, setLoading] = useState(false);
  const [apiFetchDone, setApiFetchDone] = useState(false);
  const [loadedFromApi, setLoadedFromApi] = useState(false);

  // Stable list of dimensions with non-trivial content.
  const dimensions = useMemo(() => {
    if (!analysis) return [];
    return Object.values(analysis.dimensions)
      .filter((d) => d && d.content && d.content.trim().length >= 12)
      .map((d) => ({ number: d.number, name: d.name, content: d.content }));
  }, [analysis]);

  // Fingerprint so we only re-synthesize when content/persona/count changes.
  const fingerprint = useMemo(
    () => `${activePersona}:${dimensions.map((d) => `${d.number}:${d.content.length}`).join('|')}`,
    [dimensions, activePersona]
  );

  const [graph, setGraph] = useState<KnowledgeGraph>(EMPTY);
  const lastFingerprint = useRef<string>('');

  // 1. API Fetching (if analysisId exists)
  useEffect(() => {
    if (!analysisId) {
      setGraph(EMPTY);
      setApiFetchDone(false);
      setLoadedFromApi(false);
      return;
    }

    let cancelled = false;
    setLoading(true);
    setApiFetchDone(false);
    setLoadedFromApi(false);
    fetch(`/api/analyses/${analysisId}/graph`)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        if (cancelled) return;
        const nodes = (data.entities || []).map((e: any) => ({
          id: e.id,
          label: e.label,
          type: e.type,
          weight: e.weight
        }));
        const edges = (data.relations || []).map((r: any) => ({
          source: r.source_entity_id,
          target: r.target_entity_id,
          strength: r.strength
        }));
        
        if (nodes.length > 0) {
          setGraph({
            nodes,
            edges,
            rootId: null
          });
          setLoadedFromApi(true);
        } else {
          setGraph(EMPTY);
          setLoadedFromApi(false);
        }
        setLoading(false);
        setApiFetchDone(true);
      })
      .catch(() => {
        if (!cancelled) {
          setGraph(EMPTY);
          setLoadedFromApi(false);
          setLoading(false);
          setApiFetchDone(true);
        }
      });

    return () => { cancelled = true; };
  }, [analysisId]);

  // 2. Client-side Synthesis (fallback/live)
  useEffect(() => {
    // If we have a high-fidelity knowledge graph generated by the worker, validate and use it directly!
    if (storeKnowledgeGraph && Array.isArray(storeKnowledgeGraph.nodes) && storeKnowledgeGraph.nodes.length > 0) {
      // Validate nodes: check required fields and skip/filter out malformed ones
      const validNodes = storeKnowledgeGraph.nodes.filter((n: any) => {
        return n && (typeof n.id === 'string' || typeof n.id === 'number') && typeof n.label === 'string';
      });

      if (validNodes.length > 0) {
        const mappedNodes: GraphNode[] = validNodes.map((n: any) => ({
          id: String(n.id),
          dimension: typeof n.dimension === 'number' ? n.dimension : DEFAULT_KG_EXTRACTION_DIMENSION,
          label: n.label,
          content: n.content || '',
          weight: typeof n.weight === 'number' ? n.weight : 1,
          polarity: typeof n.polarity === 'number' ? n.polarity : 0,
          keyTerms: Array.isArray(n.keyTerms) ? n.keyTerms : [],
          inPersona: typeof n.inPersona === 'boolean' ? n.inPersona : true,
        }));

        // Validate edges: check required fields and filter out malformed ones
        const rawEdges = Array.isArray(storeKnowledgeGraph.edges) ? storeKnowledgeGraph.edges : [];
        const validEdges = rawEdges.filter((e: any) => {
          return e && (typeof e.source === 'string' || typeof e.source === 'number') && (typeof e.target === 'string' || typeof e.target === 'number');
        });

        const mappedEdges: GraphEdge[] = validEdges.map((e: any) => ({
          source: String(e.source),
          target: String(e.target),
          strength: typeof e.strength === 'number' ? e.strength : 1,
          kind: e.kind || 'related',
        }));

        // Derive rootId: use storeKnowledgeGraph.rootId if valid, else derive from the first valid mapped node
        let resolvedRootId = storeKnowledgeGraph.rootId;
        const nodeIds = new Set(mappedNodes.map((n) => n.id));

        if (!resolvedRootId || !nodeIds.has(resolvedRootId)) {
          resolvedRootId = mappedNodes[0]?.id || null;
        }

        setGraph({
          nodes: mappedNodes,
          edges: mappedEdges,
          rootId: resolvedRootId,
        });
        return;
      }
    }

    // If analysisId exists, only fall back to client-side synthesis if API fetch finished and returned no nodes
    if (analysisId) {
      if (!apiFetchDone) return;
      if (loadedFromApi) return;
    }

    if (dimensions.length < 1) {
      setGraph(EMPTY);
      lastFingerprint.current = '';
      return;
    }
    if (fingerprint === lastFingerprint.current) return;

    let cancelled = false;
    synthesizer
      .synthesize({ dimensions, personaDimensions: PERSONA_DIMENSIONS[activePersona] })
      .then((g) => {
        if (cancelled) return;
        lastFingerprint.current = fingerprint;
        setGraph(g);
      })
      .catch(() => {
        if (!cancelled) setGraph(EMPTY);
      });

    return () => {
      cancelled = true;
    };
  }, [fingerprint, dimensions, activePersona, analysisId, apiFetchDone, loadedFromApi, storeKnowledgeGraph]);

  return { graph, ready: graph.nodes.length >= 1, loading };
}
