-- R3b step 2.1 cleanup: drop the legacy 2-column unique key on analysis_chunks
-- now that the code writes/reads with the 3-column matrix key
-- (analysis_id, jev_chunk_index, chunk_index) -- see migration
-- 20260930180000_analyses_stream_count_and_chunk_matrix.sql.
--
-- DEPLOYMENT ORDERING (hard requirement): apply this ONLY AFTER the web build
-- that carries the 3-column-key code is deployed to production. Dropping
-- unique_analysis_chunk while the old code (which upserts with
-- onConflict: 'analysis_id,chunk_index') is still live makes every chunk
-- upsert fail with "there is no unique or exclusion constraint matching the
-- ON CONFLICT specification".
