/**
 * Model bake-off evaluation script (ADR 034 evaluation tooling).
 *
 * Compares candidate models (`openai/gpt-oss-120b`, `z-ai/glm-5.3-flash`)
 * against EXISTING production outputs stored in the DB — the benchmark rows
 * are NEVER regenerated. Per the dispatch contract:
 *   - Benchmark = existing analyses rows whose main 11-dimension analysis was
 *     generated by Claude Haiku 4.5 (`model_used` ilike '%haiku%').
 *   - For Dimension 0 (executive_digest) the stored digest on those rows is
 *     itself `openai/gpt-oss-120b` output (verified live 2026-09-26:
 *     executive_digest->>'model' = 'openai/gpt-oss-120b' on every eligible
 *     row) — so for Dim 0 the benchmark is the GPT-OSS production baseline,
 *     and the script labels each benchmark with the model that actually
 *     produced it (from DB fields, never assumed).
 *
 * Deterministic comparison metrics (no extra LLM calls by default):
 *   - length ratio, lexical token Jaccard + bigram overlap (semantic proxy),
 *   - required-subsection presence (formatting consistency),
 *   - markdown heading-structure similarity and numeric-entity overlap (style).
 * Optional `--judge` adds an LLM semantic-fidelity judge call. The judge is a
 * NEW role (a separate scoring call); the benchmark outputs themselves are
 * still never regenerated.
 *
 * Usage:
 *   set -a; source /path/to/.env.local; set +a
 *   pnpm dlx tsx scripts/research/run-model-bakeoff.ts --dry-run   # connectivity only, zero generation
 *   pnpm dlx tsx scripts/research/run-model-bakeoff.ts --dims 0,6 --limit 12
 *
 * Required env: SUPABASE_ACCESS_TOKEN, NEXT_PUBLIC_SUPABASE_URL, OPENROUTER_API_KEY
 * (loaded from repo-root .env.local automatically if present; values never printed).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Leaf prompt modules only — importing executive-digest.ts wholesale would
// pull its lazy '@/...' dynamic import → next/headers, which needs web's full
// compiler context for a standalone type-check.
import { decodeFallback } from '../../web/lib/prompts/fallback-loader.js';
import { EXECUTIVE_DIGEST_FALLBACK_B64 } from '../../web/lib/prompts/fallbacks/executive-digest.fallback.js';
import { UCIS_V5_3_SYSTEM } from '../../web/lib/prompts/ucis-v5.3.js';

// Byte-identical to production: web/lib/prompts/executive-digest.ts:33
// `export const EXECUTIVE_DIGEST_SYSTEM_FALLBACK = decodeFallback(EXECUTIVE_DIGEST_FALLBACK_B64)`.
const EXECUTIVE_DIGEST_SYSTEM_FALLBACK = decodeFallback(EXECUTIVE_DIGEST_FALLBACK_B64);

interface ExecutiveDigest {
  snapshot: string;
  /** Stored DB rows hold string[]; extracted tiers are raw text. */
  takeaways: string | string[];
  overview: string;
  detailedSummary: string;
}

/**
 * Faithful port of web/lib/prompts/executive-digest.ts truncateForDigest()
 * (verbatim logic) + buildExecutiveDigestUserMessage() — ported (not imported)
 * only because the real module's lazy '@/...' dynamic import cannot resolve in
 * a standalone script type-check; prior fidelity tests used the same ported
 * approach (docs/research/2026-08-17-digest-regeneration-fidelity-test.md).
 */
function truncateForDigest(markdown: string, maxChars = 18000): string {
  if (!markdown) return '';
  if (markdown.length <= maxChars) return markdown.trim();
  const dimRegex = /##+\s*Dimension\s+\d+[\s\S]*?(?=##+\s*Dimension\s+\d+|$)/gi;
  const dims = markdown.match(dimRegex) || [];
  let out = '';
  for (const dim of dims) {
    if (out.length + dim.length > maxChars) break;
    out += dim;
  }
  return (out || markdown.slice(0, maxChars)).trim();
}

function buildExecutiveDigestUserMessage(analysisMarkdown: string): string {
  const safe = truncateForDigest(analysisMarkdown, 18000);
  return `Here is the completed 11-dimension analysis to digest:\n\n${safe.trim()}`;
}

/**
 * Local digest-tier extractor using the SAME four tier-header regexes as
 * production (web/lib/prompts/executive-digest.ts DIGEST_HEADERS, copied
 * verbatim) — a reduced parseExecutiveDigest() returning raw tier text
 * (production's bullet-stripping is a render detail, irrelevant for metrics).
 */
const DIGEST_HEADERS: Array<{ key: keyof ExecutiveDigest; headerRe: RegExp }> = [
  { key: 'snapshot', headerRe: /(?:^|\n)\s*(?:####\s*0\.1\b[^\n]*|(?:snapshot|ملخص\s*سريع|لمحة)\s*[:\n])/imu },
  { key: 'overview', headerRe: /(?:^|\n)\s*(?:####\s*0\.2\b[^\n]*|(?:overview|نظرة\s*عامة|ملخص\s*عام)\s*[:\n])/imu },
  { key: 'takeaways', headerRe: /(?:^|\n)\s*(?:####\s*0\.3\b[^\n]*|(?:key\s*takeaways|takeaways|الاستنتاجات|نقاط\s*رئيسية)\s*[:\n])/imu },
  { key: 'detailedSummary', headerRe: /(?:^|\n)\s*(?:####\s*0\.4\b[^\n]*|(?:detailed\s*summary|تفصيلي|تفاصيل|ملخص\s*مفصل)\s*[:\n])/imu },
];

function extractDigestTiers(raw: string | null | undefined): ExecutiveDigest | null {
  if (!raw || !raw.trim()) return null;
  let markdown = raw.trim();
  if (markdown.startsWith('```')) {
    markdown = markdown.replace(/^```[a-z]*\n?/i, '').replace(/```\s*$/i, '').trim();
  }
  const tiers = new Map<keyof ExecutiveDigest, number>();
  for (const h of DIGEST_HEADERS) {
    const m = markdown.match(h.headerRe);
    if (m && m.index !== undefined) tiers.set(h.key, m.index + m[0].length);
  }
  if (tiers.size === 0) return null;
  const ordered = [...tiers.entries()].sort((a, b) => a[1] - b[1]);
  const out: Partial<ExecutiveDigest> = {};
  for (let i = 0; i < ordered.length; i++) {
    const [key, start] = ordered[i];
    const end = i + 1 < ordered.length ? ordered[i + 1][1] : markdown.length;
    out[key] = markdown.slice(start, end).trim();
  }
  return out as ExecutiveDigest;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

// ---------------------------------------------------------------------------
// Env loading (dotenv-lite; never logs values)
// ---------------------------------------------------------------------------
const envFile = process.env.BAKEOFF_ENV_FILE ?? path.join(ROOT, '.env.local');
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, 'utf-8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !m[1].startsWith('#') && process.env[m[1]] === undefined) {
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
}

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v) {
    console.error(`[bakeoff] Missing required env var: ${name} (set it in the shell or ${envFile})`);
    process.exit(1);
  }
  return v;
}

const SUPABASE_ACCESS_TOKEN = requireEnv('SUPABASE_ACCESS_TOKEN');
const SUPABASE_URL = requireEnv('NEXT_PUBLIC_SUPABASE_URL');
const OPENROUTER_API_KEY = requireEnv('OPENROUTER_API_KEY');

const PROJECT_REF = (() => {
  const m = SUPABASE_URL.match(/https:\/\/([a-z0-9]+)\.supabase\.(co|com)/i);
  if (!m) {
    console.error(`[bakeoff] Could not parse project ref from NEXT_PUBLIC_SUPABASE_URL`);
    process.exit(1);
  }
  return m[1];
})();

// ---------------------------------------------------------------------------
// CLI flags
// ---------------------------------------------------------------------------
const args = process.argv.slice(2);
const flag = (name: string, fallback: string): string => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] && !args[i + 1].startsWith('--') ? args[i + 1] : fallback;
};
const hasFlag = (name: string): boolean => args.includes(`--${name}`);

const DRY_RUN = hasFlag('dry-run');
const USE_JUDGE = hasFlag('judge');
const DAYS = Number(flag('days', '60'));
const LIMIT = Number(flag('limit', '12'));
const DIMS = flag('dims', '0,6')
  .split(',')
  .map((d) => Number(d.trim()))
  .filter((d) => Number.isInteger(d) && d >= 0 && d <= 11);
const OUT_PATH = flag('out', path.join(ROOT, 'docs/research', `bakeoff-report-${new Date().toISOString().slice(0, 10)}.json`));

const CANDIDATE_MODELS = ['openai/gpt-oss-120b', 'z-ai/glm-5.3-flash'] as const;
// Digest completion budget — mirrors the live Settings Registry key
// `digest.maxOutputTokens` (default 6000; the 2000 legacy value was proven to
// truncate real digests, see ADR ledger 2026-08-17). Dimension generations use
// the production LLM cascade cap (LLMCascade.ts MAX_TOKENS_FALLBACK = 16000).
const DIGEST_MAX_TOKENS = 6000;
const DIM_MAX_TOKENS = 16000;
const TEMPERATURE = 0.3; // matches the production cascade + prior fidelity-test methodology

// ---------------------------------------------------------------------------
// Supabase Management API access (same pattern as prior research scripts)
// ---------------------------------------------------------------------------
async function dbQuery<T = unknown>(query: string): Promise<T[]> {
  const res = await fetch(`https://api.supabase.com/v1/projects/${PROJECT_REF}/database/query`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${SUPABASE_ACCESS_TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  if (!res.ok) {
    throw new Error(`DB query failed: ${res.status} ${(await res.text()).slice(0, 300)}`);
  }
  return (await res.json()) as T[];
}

interface BenchmarkRow {
  id: string;
  video_id: string;
  title: string;
  created_at: string;
  model_used: string;
  analysis_markdown: string;
  analysis_payload: { dimensions?: Array<{ number: number; content: string }> } | null;
  executive_digest: (ExecutiveDigest & { model?: string; created_at?: string }) | null;
  transcript: string;
}

async function loadBenchmarkRows(): Promise<BenchmarkRow[]> {
  const rows = await dbQuery<BenchmarkRow>(`
    select a.id, a.video_id, a.title, a.created_at, a.model_used,
           a.analysis_markdown, a.analysis_payload, a.executive_digest,
           t.content as transcript
    from analyses a
    join transcripts t on t.video_id = a.video_id
      and t.content is not null and length(t.content) > 500
    where a.model_used ilike '%haiku%'
      and a.created_at > now() - interval '${DAYS} days'
      and a.analysis_markdown is not null
      and length(a.analysis_markdown) > 10000
      and a.validation_passed is not false
    order by a.created_at desc
    limit ${LIMIT}
  `);
  // Transcript retention is 72h (ADR 012), so eligible candidates shrink fast.
  // Fail loudly with a real count instead of silently benchmarking 2 rows.
  if (rows.length < 5) {
    console.warn(`[bakeoff] WARNING: only ${rows.length} eligible rows have intact transcripts (72h retention, ADR 012). Scores from <10 rows are indicative only.`);
  }
  return rows;
}

// ---------------------------------------------------------------------------
// Prompt construction — dimension path reuses the real UCIS v5.3 system prompt
// + the production PromptBuilder bundle-segmentation (worker/src/services/PromptBuilder.ts)
// ---------------------------------------------------------------------------
const DIMENSION_NAMES: Record<number, string> = {
  1: 'APEX INTELLIGENCE', 2: 'PROVENANCE, METADATA & VIRALITY PROFILE',
  3: 'CONTENT ARCHITECTURE & FIRST PRINCIPLES', 4: 'PSYCHOLOGICAL & RHETORICAL LAYER',
  5: 'CORE INTELLIGENCE EXTRACTION', 6: 'COMPARATIVE & QUANTITATIVE ANALYSIS',
  7: 'IMPLEMENTATION SYSTEMS & WORKFLOWS', 8: 'SEMANTIC & KNOWLEDGE GRAPH FOUNDATION',
  9: 'FORWARD INTELLIGENCE & STRATEGIC FORESIGHT', 10: 'CREDIBILITY, RISK & META-ASSESSMENT',
  11: 'COMMERCIAL YIELD & MONETIZATION PROFILING',
};

const BUNDLES: number[][] = [[1, 10], [7], [8], [2, 4, 6], [5, 7], [3, 9, 11]];
const EXTRA_FIELDS: Record<number, string[]> = {
  1: ['persona'], 8: ['knowledgeGraph'], 11: ['classification', 'monetizationVerdict'],
};
const REQUIRED_SUBSECTIONS: Record<number, string[]> = {
  2: ['2.1 Header Intelligence', '2.2 Engagement & Virality Metrics', '2.3 Channel Authority Assessment', '2.4 Audience Sentiment Prediction'],
  4: ['4.1 Sentiment & Tonal Profile', '4.2 Persuasion Strategy', '4.3 Bias Detection & Critical Assessment'],
  6: ['6.1 Comparison Tables', '6.2 Scenario Analysis'],
  1: ['[EXECUTIVE_SUMMARY]', '[SHORT_SUMMARY]', '[LONG_SUMMARY]'],
  3: ['3.1 Executive Overview', '3.2 First Principles Deconstruction', '3.3 Temporal Content Map & Arc Analysis'],
  5: ['5.1 Priority Insights Matrix', '5.2 Power Quotes Library', '5.3 Referenced Entities'],
  7: ['7.1 Implementation Systems', '7.2 Execution Sequencing & Dependencies'],
  8: ['8.1 Primary Knowledge Graph Nodes', '8.2 Semantic Relations', '8.3 Cross-Domain Bridges', '8.4 Discovery Pathways'],
  9: ['9.1 Trend Projections', '9.2 Identified Gaps', '9.3 Unconventional Tangents & Cross-Domain Applications'],
  10: ['10.1 Recommendation Credibility Score', '10.2 Domain-Specific Risk Disclosures', '10.3 Final Classification'],
  11: ['11.1 AdSense RPM & Display Revenue Potential', '11.2 Sponsorship & Brand Partnership CPM', '11.3 Lead Generation & Service Monetization Value'],
};

const GUARDRAIL = `HALLUCINATION GUARDRAIL: Do not fabricate ungrounded numbers, statistics, or facts not supported by the transcript or reasonable inference from it. Reasoned estimates derived from real signals in the transcript (audience size/niche, content category, engagement patterns, production quality) are acceptable and expected wherever a dimension calls for estimation. For content that is genuinely non-monetizable or non-forecastable, use N/A or invoke the Insufficient Data Protocol rather than inventing a figure.`;

function bundleFor(dim: number): number[] {
  const found = BUNDLES.find((b) => b.includes(dim));
  if (!found) throw new Error(`No production bundle covers dimension ${dim}`);
  return found;
}

function checklistFor(dims: number[]): string {
  const list = dims.flatMap((d) => (REQUIRED_SUBSECTIONS[d] ?? []).map((s) => `D${d}: ${s}`)).join('; ');
  return `SELF-VERIFICATION CHECKLIST (perform this silently against your own draft before emitting final output; do not mention having done it): For each dimension listed above, confirm your draft contains a clearly labeled entry for every one of these required subsections: ${list}. If any required subsection is missing from your draft, add it now (using the Insufficient Data Protocol from section 0.6 if the transcript genuinely lacks the content) before finalizing your response.`;
}

function buildDimensionPrompt(dim: number, transcript: string, title: string): string {
  const bundle = bundleFor(dim);
  const metadataJson = JSON.stringify({ title, channelTitle: '', viewCount: '', likeCount: '', commentCount: '', publishedAt: '', duration: 'Unknown' }, null, 2);
  const dimLabels = bundle.map((d) => `- ### DIMENSION ${d} - ${DIMENSION_NAMES[d]}`).join('\n');
  const label = bundle.length === 1 ? `DIMENSION ${bundle[0]}` : `DIMENSIONS ${bundle.join(', ')}`;
  const extraParts: string[] = [];
  for (const d of bundle) {
    for (const f of EXTRA_FIELDS[d] ?? []) {
      if (f === 'persona') extraParts.push('include the "persona" configuration block in the JSON root');
      if (f === 'knowledgeGraph') extraParts.push('generate and include the full "knowledgeGraph" object in the JSON root (max 15 nodes, 20 edges)');
      if (f === 'classification') extraParts.push('generate and include the full "classification" object in the JSON root');
      if (f === 'monetizationVerdict') extraParts.push('generate and include the full "monetizationVerdict" object in the JSON root');
    }
  }
  const extraFieldsInstruction = extraParts.length > 0
    ? `You must also ${extraParts.join(', and ')}.`
    : 'Additionally, do NOT include persona, knowledgeGraph, classification, or monetizationVerdict fields.';
  const fallbackInstructions = 'If insufficient data exists for any dimension, invoke the Insufficient Data Protocol (section 0.6) and provide a brief explanation in the content field rather than leaving it empty. Never output empty dimensions arrays; always include dimension objects with at least a summary note.';

  return `${UCIS_V5_3_SYSTEM}

---

## ACTIVE ANALYSIS SESSION

**Metadata JSON Blob**:
\`\`\`json
${metadataJson}
\`\`\`

**Persona Configuration**:
- CREATOR: Creator (Weight: 100%)

**Timezone**: UTC

**Transcript**:
${transcript.slice(0, 48000)}${transcript.length > 48000 ? '\n\n[...transcript truncated to 48K characters...]' : ''}

---
CRITICAL INSTRUCTION FOR THIS SEGMENT ANALYSIS (${label}):
You are performing a segmented analysis of the content. For this request, you must ONLY generate the following dimension(s):
${dimLabels}

Your output JSON object must ONLY include these dimension(s) inside the "dimensions" array. Start the JSON envelope structure with "schemaVersion": "2.0". ${extraFieldsInstruction}
Your response must enforce a strict maximum output restriction of 400 analytical words per dimension.
${fallbackInstructions}
Do NOT output any other dimensions. Do NOT include any other JSON root fields. Your response must be strict, raw JSON without markdown formatting. Ensure that your output strictly matches this layout.

---
${GUARDRAIL}

${checklistFor(bundle)}`;
}

// ---------------------------------------------------------------------------
// OpenRouter generation
// ---------------------------------------------------------------------------
interface CompletionResult {
  text: string;
  finishReason: string;
  usage: { promptTokens: number; completionTokens: number; costUsd: number | null };
  model: string;
}

async function generate(model: string, system: string, user: string, maxTokens: number): Promise<CompletionResult> {
  const messages: Array<{ role: string; content: string }> = [];
  if (system) messages.push({ role: 'system', content: system });
  messages.push({ role: 'user', content: user });
  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: { Authorization: `Bearer ${OPENROUTER_API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ model, temperature: TEMPERATURE, max_tokens: maxTokens, messages }),
  });
  if (!res.ok) {
    throw new Error(`OpenRouter generation failed (${model}): ${res.status} ${(await res.text()).slice(0, 300)}`);
  }
  const data = await res.json();
  const choice = data?.choices?.[0];
  return {
    text: choice?.message?.content ?? '',
    finishReason: choice?.finish_reason ?? 'unknown',
    usage: {
      promptTokens: data?.usage?.prompt_tokens ?? 0,
      completionTokens: data?.usage?.completion_tokens ?? 0,
      costUsd: data?.usage?.cost ?? null,
    },
    model: data?.model ?? model,
  };
}

async function judge(reference: string, candidate: string): Promise<{ score: number; notes: string } | null> {
  const system = 'You are a strict but fair evaluation judge. Compare a CANDIDATE analysis output against a REFERENCE output produced from the same transcript. Score semantic fidelity 0-100 (does the candidate cover the same substantive claims, numbers, entities and structure as the reference, regardless of wording?) and respond ONLY with JSON: {"score": <0-100>, "notes": "<one sentence>"}.';
  const user = `REFERENCE:\n${reference.slice(0, 12000)}\n\nCANDIDATE:\n${candidate.slice(0, 12000)}`;
  try {
    const r = await generate('anthropic/claude-haiku-4.5', system, user, 1000);
    const m = r.text.match(/\{[\s\S]*\}/);
    if (!m) return null;
    const parsed = JSON.parse(m[0]) as { score: number; notes: string };
    return { score: Number(parsed.score), notes: String(parsed.notes) };
  } catch (err) {
    console.warn(`[bakeoff] judge call failed: ${err instanceof Error ? err.message : String(err)}`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// Deterministic comparison metrics
// ---------------------------------------------------------------------------
function tokenize(s: string): string[] {
  return s.toLowerCase().match(/[\p{L}\p{N}]+/gu) ?? [];
}

function jaccard(a: string[], b: string[]): number {
  const A = new Set(a);
  const B = new Set(b);
  if (A.size === 0 && B.size === 0) return 1;
  let inter = 0;
  for (const t of A) if (B.has(t)) inter += 1;
  return inter / (A.size + B.size - inter);
}

function bigramOverlap(a: string[], b: string[]): number {
  const bg = (t: string[]): Set<string> => new Set(t.slice(1).map((w, i) => `${t[i]} ${w}`));
  return jaccard([...bg(a)], [...bg(b)]);
}

function numericOverlap(ref: string, cand: string): number {
  const nums = (s: string) => new Set(s.match(/\d[\d.,]*%?/g) ?? []);
  const A = nums(ref);
  const B = nums(cand);
  if (A.size === 0) return 1; // nothing numeric to preserve
  let inter = 0;
  for (const n of A) if (B.has(n)) inter += 1;
  return inter / A.size;
}

function headingStructure(s: string): string[] {
  return (s.match(/^#{1,6}\s.*$|^\*\*[^*\n]+\*\*\s*:?\s*$/gmu) ?? []).map((h) => h.toLowerCase().replace(/\s+/g, ' ').trim());
}

function subsectionPresence(ref: string, cand: string, dim: number): { required: number; presentRef: number; presentCand: number } {
  const reqs = REQUIRED_SUBSECTIONS[dim] ?? [];
  const hay = (s: string) => s.toLowerCase();
  const presentRef = reqs.filter((r) => hay(ref).includes(r.toLowerCase())).length;
  const presentCand = reqs.filter((r) => hay(cand).includes(r.toLowerCase())).length;
  return { required: reqs.length, presentRef, presentCand };
}

interface DimComparison {
  rowId: string;
  videoId: string;
  title: string;
  createdAt: string;
  dimension: number;
  benchmarkModel: string;
  benchmarkChars: number;
  candidates: Array<{
    model: string;
    finishReason: string;
    chars: number;
    lengthRatio: number;
    tokenJaccard: number;
    bigramOverlap: number;
    numericOverlap: number;
    headingSim: number;
    subsections: { required: number; presentRef: number; presentCand: number };
    judgeScore: number | null;
    judgeNotes: string | null;
    costUsd: number | null;
    error: string | null;
  }>;
}

function headingSim(ref: string, cand: string): number {
  return jaccard(headingStructure(ref), headingStructure(cand));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function verifyConnectivity(): Promise<void> {
  const keyRes = await fetch('https://openrouter.ai/api/v1/key', {
    headers: { Authorization: `Bearer ${OPENROUTER_API_KEY}` },
  });
  if (!keyRes.ok) throw new Error(`OpenRouter auth check failed: ${keyRes.status}`);
  const keyData = await keyRes.json();
  const limit = keyData?.data?.limit;
  const usage = keyData?.data?.usage;
  console.log(`[bakeoff] OpenRouter auth OK (usage=${typeof usage === 'number' ? usage : 'n/a'}, limit=${limit === null ? 'unlimited' : (limit ?? 'n/a')})`);
  const modelsRes = await fetch('https://openrouter.ai/api/v1/models');
  if (!modelsRes.ok) throw new Error(`OpenRouter model catalog fetch failed: ${modelsRes.status}`);
  const catalog = await modelsRes.json();
  const ids = new Set<string>((catalog?.data ?? []).map((m: { id: string }) => m.id));
  for (const m of [`${CANDIDATE_MODELS[0]}`, `${CANDIDATE_MODELS[1]}`, 'anthropic/claude-haiku-4.5']) {
    console.log(`[bakeoff] model ${m}: ${ids.has(m) ? 'in catalog' : 'NOT in catalog (will 404 at generation)'}`);
  }
  const probe = await dbQuery('select 1 as ok');
  console.log(`[bakeoff] Supabase DB OK (project ${PROJECT_REF}, probe=${JSON.stringify(probe)})`);
}

async function main(): Promise<void> {
  console.log(`[bakeoff] mode=${DRY_RUN ? 'DRY-RUN (connectivity only, zero generation cost)' : 'LIVE'} dims=${DIMS.join(',')} days=${DAYS} limit=${LIMIT} judge=${USE_JUDGE}`);
  await verifyConnectivity();
  if (DRY_RUN) {
    const rows = await loadBenchmarkRows();
    console.log(`[bakeoff] DRY-RUN: ${rows.length} eligible benchmark rows found:`);
    for (const r of rows) {
      console.log(`  - ${r.video_id} | ${r.created_at.slice(0, 10)} | model_used="${r.model_used}" | digest_model="${r.executive_digest?.model ?? 'n/a'}" | md=${r.analysis_markdown.length}ch | transcript=${r.transcript.length}ch | ${r.title}`);
    }
    console.log('[bakeoff] DRY-RUN complete. No generation performed. Re-run without --dry-run to execute.');
    return;
  }

  const rows = await loadBenchmarkRows();
  const report: Array<DimComparison> = [];
  for (const row of rows) {
    for (const dim of DIMS) {
      const entry: DimComparison = {
        rowId: row.id, videoId: row.video_id, title: row.title, createdAt: row.created_at,
        dimension: dim, benchmarkModel: dim === 0 ? (row.executive_digest?.model ?? 'unknown') : row.model_used,
        benchmarkChars: dim === 0 ? JSON.stringify(row.executive_digest ?? {}).length : (row.analysis_payload?.dimensions?.find((d) => d.number === dim)?.content?.length ?? 0),
        candidates: [],
      };

      let referenceText: string;
      let systemPrompt: string;
      let userPrompt: string;
      let maxTokens: number;
      if (dim === 0) {
        if (!row.executive_digest) {
          console.warn(`[bakeoff] skip ${row.video_id} dim0: no stored executive_digest`);
          continue;
        }
        referenceText = JSON.stringify(row.executive_digest);
        systemPrompt = EXECUTIVE_DIGEST_SYSTEM_FALLBACK;
        userPrompt = buildExecutiveDigestUserMessage(row.analysis_markdown);
        maxTokens = DIGEST_MAX_TOKENS;
      } else {
        const refDim = row.analysis_payload?.dimensions?.find((d) => d.number === dim);
        if (!refDim?.content || !row.transcript) {
          console.warn(`[bakeoff] skip ${row.video_id} dim${dim}: missing stored dimension content or transcript`);
          continue;
        }
        referenceText = refDim.content;
        systemPrompt = '';
        userPrompt = buildDimensionPrompt(dim, row.transcript, row.title);
        maxTokens = DIM_MAX_TOKENS;
      }
      entry.benchmarkChars = referenceText.length;

      for (const model of CANDIDATE_MODELS) {
        try {
          const result = await generate(model, systemPrompt, userPrompt, maxTokens);
          let candidateText = result.text;
          if (dim === 0) {
            const parsed = extractDigestTiers(result.text);
            candidateText = parsed ? JSON.stringify(parsed) : result.text;
          } else {
            const m = result.text.match(/\{[\s\S]*\}/);
            if (m) {
              try {
                const envelope = JSON.parse(m[0]) as { dimensions?: Array<{ number: number; content: string }> };
                const c = envelope.dimensions?.find((d) => d.number === dim)?.content;
                if (c) candidateText = c;
              } catch { /* keep raw text for metrics */ }
            }
          }
          const refTokens = tokenize(referenceText);
          const candTokens = tokenize(candidateText);
          const j = USE_JUDGE ? await judge(referenceText, candidateText) : null;
          entry.candidates.push({
            model,
            finishReason: result.finishReason,
            chars: candidateText.length,
            lengthRatio: referenceText.length > 0 ? candidateText.length / referenceText.length : 0,
            tokenJaccard: Number(jaccard(refTokens, candTokens).toFixed(4)),
            bigramOverlap: Number(bigramOverlap(refTokens, candTokens).toFixed(4)),
            numericOverlap: Number(numericOverlap(referenceText, candidateText).toFixed(4)),
            headingSim: Number(headingSim(referenceText, candidateText).toFixed(4)),
            subsections: dim === 0 ? { required: 4, presentRef: 4, presentCand: (Object.values(extractDigestTiers(candidateText) ?? {}).filter(Boolean).length) } : subsectionPresence(referenceText, candidateText, dim),
            judgeScore: j?.score ?? null,
            judgeNotes: j?.notes ?? null,
            costUsd: result.usage.costUsd,
            error: null,
          });
        } catch (err) {
          entry.candidates.push({
            model, finishReason: 'error', chars: 0, lengthRatio: 0, tokenJaccard: 0, bigramOverlap: 0,
            numericOverlap: 0, headingSim: 0,
            subsections: { required: 0, presentRef: 0, presentCand: 0 },
            judgeScore: null, judgeNotes: null, costUsd: null,
            error: err instanceof Error ? err.message : String(err),
          });
        }
      }
      report.push(entry);
      console.log(`[bakeoff] ${row.video_id} dim${dim}: ${entry.candidates.map((c) => `${c.model.split('/').pop()} j=${c.tokenJaccard} sub=${c.subsections.presentCand}/${c.subsections.required}${c.judgeScore !== null ? ` judge=${c.judgeScore}` : ''}`).join(' | ')}`);
    }
  }

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, JSON.stringify({ generatedAt: new Date().toISOString(), dims: DIMS, days: DAYS, limit: LIMIT, judge: USE_JUDGE, report }, null, 2));
  console.log(`[bakeoff] Report written to ${OUT_PATH}`);

  // Aggregate summary per candidate model
  for (const model of CANDIDATE_MODELS) {
    const all = report.flatMap((e) => e.candidates.filter((c) => c.model === model && !c.error));
    if (all.length === 0) continue;
    const mean = (f: (c: (typeof all)[number]) => number) => all.reduce((s, c) => s + f(c), 0) / all.length;
    console.log(`[bakeoff] SUMMARY ${model}: n=${all.length} tokenJaccard=${mean((c) => c.tokenJaccard).toFixed(3)} bigram=${mean((c) => c.bigramOverlap).toFixed(3)} numeric=${mean((c) => c.numericOverlap).toFixed(3)} heading=${mean((c) => c.headingSim).toFixed(3)} lenRatio=${mean((c) => c.lengthRatio).toFixed(2)}${USE_JUDGE ? ` judge=${mean((c) => c.judgeScore ?? 0).toFixed(1)}` : ''}`);
  }
}

main().catch((err) => {
  console.error(`[bakeoff] FATAL: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});